version: '3'
services:
  web: #one container hosting dev server
    build:
      context: . #current directory
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
    - /app/node_modules
    - .:/app
  tests: #one container hosting tests execution
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes: #volumes is added that every time a file changes, it will be refreshed
    - /app/node_modules
    - .:/app
    command: ["npm", "run", "test"]


#docker-compose up --build (builds a new container image)
